### PR TITLE
Add support for v12

### PR DESCRIPTION
**Pull request by spoonerWeb**
* Add Services.yaml file
* Remove usage of ObjectManager
* Rename TypoScript file
* Remove superfluous vendor name in form yaml
* Remove support for v10 and v11

### CODE REVIEW

**Comment by fritzdacat** [comment]
What are the plans for TYPO3 12? There is this branch of "spoonerWeb"?

**Comment by kreiseuskirchen** [comment]
I would like that too.

**Comment by fritzdacat** [comment]
Are there any plans for a TYPO3 12 release?

**Comment by spoonerWeb** [comment]
@akiessling Resolved the conflicts.

**Comment by akiessling** [comment]
Uuuh, sorry, that pull request totally slipped through. I can't find any notification mails in my inbox  besides the last comment from @spoonerWeb 
I will try to have a look this week!

**Comment by akiessling** [comment]
The updated code looks good so far. I'm not sure about the mixin part in the yaml file: That was dropped / refactored in EXT:form some versions ago and thus the propertyValidators won't kick in anymore.
But since the recipient config was changed from single to multiple, there does not seem to be any validation for the fields at all anymore? Back in 8.7 i extended this mixin https://github.com/TYPO3/typo3/blob/9e1c91aed86490f75730ae186504bd900057107e/typo3/sysext/form/Configuration/Yaml/FormEditorSetup.yaml#L1161 so you had to enter a valid email, or it had to be some form variable --> now i can enter any string and save the form. The mail will obviously not be sent anywhere then. The yaml config has a type email configured, no idea what that is supposed to validate in the form manager. 
So we should probably drop the mixin config and the according JS code --> any objections?

**Comment by akiessling** [comment]
FYI: Release of the new version will probably happen tomorrow

**Pull request merged**
